// Safe accessors for the mascot globals defined by static/mascots.js
// (generated by build_setup.py; any of them may be absent in dev).
'use strict';

const _g = typeof globalThis !== 'undefined' ? globalThis : window;
const _mc = (name) => (typeof _g[name] !== 'undefined' ? _g[name] : null);

export const MASCOT_DJ = _mc('MASCOT_DJ');
export const MASCOT_VIBING = _mc('MASCOT_VIBING');
export const MASCOT_CHILLING = _mc('MASCOT_CHILLING');
export const MASCOT_FRUSTRATED = _mc('MASCOT_FRUSTRATED');
export const MASCOT_TIRED = _mc('MASCOT_TIRED');
export const MASCOT_COMFY_SAFE = _mc('MASCOT_COMFY');
export const MASCOT_SUCCESS_SAFE = _mc('MASCOT_SUCCESS');
export const MASCOT_TROUBLESHOOTING_SAFE = _mc('MASCOT_TROUBLESHOOTING');
export const MASCOT_VICTORY_SAFE = _mc('MASCOT_VICTORY');
